# Generated by Django 5.0.6 on 2024-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_alter_stock_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
