# Generated by Django 5.0.6 on 2024-07-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_supplier_company_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
